### ISSUE TITLE
Convert between Token Units

### ISSUE THREAD

**Issue by Sladuca** [bafnetwork/baf-wallet-v2#57]
We should convert to/from the "really big number" representation (i.e. wei, yoctoNEAR, lamports, etc) whenever we:
* display amounts
* collect amount from forms

The best place to put this functionality is probably the [`Converter` sub-interface of `ChainInterface`](https://github.com/bafnetwork/baf-wallet-v2/blob/646ac4641328b7972db7ede9decfbeeb8ac46cd0/libs/interfaces/src/lib/chains.ts#L165) so that chain implementations can be expected to implement this function.

### Tasks
- [ ] add two function types to `Converter`, one for going each way
- [ ] implement these functions in [`nearConverter`](https://github.com/bafnetwork/baf-wallet-v2/blob/646ac4641328b7972db7ede9decfbeeb8ac46cd0/libs/near/src/lib/convert.ts#L11) converting between YoctoNEAR and NEAR
- [ ] use them in the UI for the amount in sendForm
